model_name_or_path: Dahoas/pythia-125M-static-sft
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  Anthropic/hh-rlhf: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 4
turn_type: single

# DPOTrainer arguments
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 4
gradient_checkpointing: true
max_steps: 3000
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: pythia-160m-rm-hh
learning_rate: 1.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
num_train_epochs: 1
optim: adamw_torch
output_dir: data/pythia-160m-rm-hh
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
push_to_hub: true
save_strategy: "steps"
save_steps: 200
save_total_limit: 1
seed: 42
warmup_ratio: 0.1