# model_name_or_path: alignment-handbook/zephyr-7b-sft-full
model_name_or_path: DatPySci/tiny-llama-sft-full
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  #HuggingFaceH4/ultrafeedback_binarized: 1.0
  generated/iter0: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: false
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
prior: 0.1
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-kto-iter0
learning_rate: 5.0e-7
run_name: zephyr-7b-kto-iter0
log_level: info
logging_steps: 5
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 1
optim: rmsprop
output_dir: data/model/zephyr-7b-kto-iter0
report_to:
- wandb
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: true
save_strategy: "steps"
save_steps: 100
loss_type: "nnpu"
save_total_limit: -1
seed: 42
warmup_ratio: 0.1